# Generated by Django 4.2.2 on 2023-07-14 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adversaire', models.CharField(max_length=15)),
                ('victoire', models.BooleanField(default=False)),
                ('ourscore', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('opp_score', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('poste', models.CharField(choices=[('M', 'Meneur'), ('A', 'Arrière'), ('AI', 'Ailier'), ('AF', 'Ailier fort'), ('P', 'Pivot')], max_length=2)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('rebounds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('assists', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('steals', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('blocks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourteam.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourteam.player')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(through='ourteam.Stats', to='ourteam.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='ourteam.Stats', to='ourteam.player'),
        ),
    ]
