# Generated by Django 4.1.7 on 2023-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_alter_player_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='victoire',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
